#!/usr/sbin/nft -f

flush ruleset

#variables
define ISP = ens3
define INT = ens4
define DMZ = ens5

table inet filter {
        chain input {
                type filter hook input priority filter;
                policy drop;
                ct state established,related accept
                iif lo accept
                tcp dport 22 accept
                iifname $INT accept
                iifname $DMZ accept
        }
        chain forward {
                type filter hook forward priority filter;
                policy drop;
                ct state established,related accept
                iifname $INT oifname $ISP accept
                iifname $DMZ oifname $ISP accept
                iifname $INT oifname $DMZ tcp dport { 80, 443 } accept
        }
        chain output {
                type filter hook output priority filter;
        }
}

#nat

table ip nat {
        chain prerouting {
                type nat hook prerouting priority -100;
        }
        chain postrouting {
                type nat hook postrouting priority 100;
                oifname $ISP ip saddr 172.88.10.0/24 masquerade
                oifname $ISP ip saddr 192.168.10.0/24 masquerade
        }
}
